project:
  type: website
  output-dir: ../_site/energybalance-slides

website:
  title: "Energy Balances — Slides"
  navbar:
    left:
      - text: "Energy Balances Slides"
        href: index.qmd
      - text: "Summary: Storing and Transferring Energy"
        href: 01-storing-energy.qmd
      - text: "Summary 2: Transferring Energy, Heat and Work"
        href: 02-transferring-energy.qmd

format:
  revealjs:
    theme: default
    slide-number: true
    toc: false
    auto-stretch: false
    css: slide_styles.css
    html-math-method: katex