project:
  type: website
  output-dir: ../_site/energybalance-slides

website:
  title: "Energy Balances — Slides"
  navbar:
    left:
      - text: "Energy Balances Slides"
        href: index.qmd
      - text: "Lecture 1: Storing and Transferring Energy"
        href: 01-introduction.qmd
      - text: "Lecture 2: First Law"
        href: 02-first-law.qmd

format:
  revealjs:
    theme: default
    slide-number: true
    toc: false
    auto-stretch: false
    css: slide_styles.css