## Example 1.2: Hydroelectric power {.unnumbered .scrollable}

A hydroelectric power station generates electricity by allowing water to fall from a height. The water is stored in a reservoir at a height of 100 m above the turbine. The flow rate of water through the turbine is 10 m³/s. The density of water is 1000 kg/m³. Calculate the power generated by the turbine.

**Solution**

::: {.fragment}
The power generated by the turbine comes from the change in potential energy of the water as it falls from the reservoir to the turbine. The potential energy of the water is given by:

$$E_p = m \cdot g \cdot z$$

where:

- $E_p$ is the potential energy (J)
- $m$ is the mass of water (kg)
- $g$ is the acceleration due to gravity (9.81 m/s²)
- $z$ is the height of the water above the turbine (m)
:::

::: {.fragment}
As power is the rate of energy transfer, we can express the power generated by the turbine as:

$$\dot{W} = \dot{m} \cdot g \cdot z$$

where:

- $\dot{W}$ is the power generated by the turbine (W)
- $\dot{m}$ is the mass flow rate of water (kg/s)
:::

::: {.fragment}
First, we need to calculate the mass flow rate of water through the turbine:

$$\dot{m} = \rho \cdot \dot{V} = 1000\ \text{kg/m³} \cdot 10\ \text{m³/s} = 10,000\ \text{kg/s}$$
:::

::: {.fragment}
Now we can calculate the power generated by the turbine:

$$\dot{W} = \dot{m} \cdot g \cdot z$$
$$\dot{W}= 10,000\ \text{kg/s} \cdot 9.81\ \text{m/s²} \cdot 100\ \text{m}$$
$$\dot{W}= 9,810,000\ \text{W} = 9.81\ \text{MW}$$
:::