## Example 2.1: Energy accumulation {.unnumbered .scrollable}

A tank contains 500 L of toluene at 80 °C. The tank is cooled to 50 °C before half the toluene is withdrawn. The energy of the toluene scales with temperature by approximately 155 J/molK (this is the heat capacity). Calculate the energy accumulated in the tank relative to its initial state. The density of toluene is 0.867 kg/L and the molar mass is 92.14 g/mol.

::: {.content-visible unless-format="revealjs"}

::: {.callout-note icon=false collapse="true" title="Solution"}

Firstly the key is to realise that the energy accumulated in the tank is the difference between the initial and final energy of the toluene in the tank. The energy of the toluene scales with temperature by approximately 155 J/molK, so we can calculate the energy change as:
$$\Delta E_{cool} = n \cdot C_p \cdot \Delta T$$

where:

- $\Delta E_{cool}$ is the change in energy due to cooling (J)
- $n$ is the number of moles of toluene
- $C_p$ is the heat capacity (J/molK)
- $\Delta T$ is the change in temperature (K)



First calculate the number of moles of toluene in the tank:

$$
\begin{aligned}
n & = \frac{m}{MW} \\
   & = \frac{500\ \text{L} \cdot 0.867\ \text{kg/L}}{92.14\ \text{g/mol} \cdot \frac{1\ \text{kg}}{1000\ \text{g}}}\\
   & = 4705.6\ \text{mol}
\end{aligned}
$$

where:

- $m$ is the mass of toluene (kg)
- $MW$ is the molar mass of toluene (kg/mol)


Now calculate the change in energy during the cooling of the toluene from 80 °C to 50 °C:

$$
\begin{aligned}
\Delta E_{cool} & = n \cdot C_p \cdot \Delta T 
                & = 4705.6\ \text{mol} \cdot 155\ \text{J/molK} \cdot (50 - 80)\ \text{K}\\
                & = -22,340,000\ \text{J}
\end{aligned}
$$


Now calculate the change in energy during the withdrawal of half the toluene from the tank. This is simply half the energy of the toluene remaining in the tank after cooling. But we need add this to the energy change from cooling to get the total energy change in the tank:

$$\Delta E_{withdrawal} = \frac{1}{2} \cdot \Delta E_{cool}$$

$$
\begin{aligned}
\Delta E_{total} & = \Delta E_{cool} + \Delta E_{withdrawal} \\
                 & = -22,340,000 + \frac{1}{2} (-22,340,000)\\
                & = -33,510,000\ \text{J}
\end{aligned}
$$

This is relative to the initial state of the toluene in the tank. The negative sign indicates that energy has been lost from the tank.

:::

:::
