project:
  type: book
  output-dir: ../_site/energybalance-book

book:
  title: "Energy Balances"
  author: "Professor Aaron Marshall"
  date: today
  chapters:
    - index.qmd
    - 01-ebal-intro.qmd
    - 02-ebal-states-phaserule.qmd
    - useful-info.qmd
    - key-terms.qmd
    - problems-solutions.qmd

format:
  html:
    theme: cosmo
    toc: true
    css: book-styles.css
    include-in-header:
      - text: |
          <script>
          window.MathJax = {
            tex: {
              macros: {
                hb: ["\\boldsymbol{#1}", 1]
              }
            }
          };
          </script>